version: '3.1'

services:

  web:
    build:
      context: blog
      dockerfile: Dockerfile
    command: php artisan serve --host 0.0.0.0
    volumes:
      - "./blog:/root/test/blog"
    ports:
      - "80:8000"

  mysql:
    image: "mysql:5.7.27"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_USER: "homestead"
      MYSQL_DATABASE: "homestead"
    ports:
      - "3306:3306"
