version: '3.1'

services:

  web:
    build:
      context: blog
      dockerfile: Dockerfile
    command: php artisan serve --host 0.0.0.0
    working_dir: "/root/test/blog"
    ports:
      - "8000:8000"
